server.port=8080
spring.application.name=customer
logging.level.root=INFO
spring.datasource.url=jdbc:postgresql://localhost:5432/customer
spring.datasource.username=amigoscode
spring.datasource.password=password
spring.datasource.driver-class-name=org.postgresql.Driver
spring.data.jdbc.dialect=postgresql
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
eureka.client.service-url.defaultZone=http://localhost:8761/eureka
eureka.client.fetch-registry=true
eureka.client.register-with-eureka=true
spring.rabbitmq.port=5672